blueprint:
  name: Device Health Report
  description: Send daily email report of low battery and unavailable devices
  domain: automation
  source_url: https://github.com/YOUR_USERNAME/ha-device-health-report/blob/main/device_health_report.yaml
  input:
    report_time:
      name: Report Time
      description: When to send the daily report
      default: "09:00:00"
      selector:
        time:
    
    battery_threshold:
      name: Battery Threshold (%)
      description: Alert when battery drops below this level
      default: 20
      selector:
        number:
          min: 5
          max: 50
          unit_of_measurement: "%"
    
    notify_service:
      name: Notification Service
      description: Email notification service (e.g., notify.email or notify.gmail)
      selector:
        text:
    
    send_only_if_issues:
      name: Send Only If Issues Found
      description: Skip email if no low batteries or unavailable devices
      default: true
      selector:
        boolean:

    exclusion_mode:
      name: Exclusion Mode
      description: How to manage excluded entities
      default: "manual"
      selector:
        select:
          options:
            - label: "Manual (comma-separated list)"
              value: "manual"
            - label: "Use Exclusions Manager Integration"
              value: "integration"

    excluded_entities:
      name: Excluded Entities (Manual Mode)
      description: "Comma-separated list of entity IDs to exclude (e.g., sensor.battery_1, sensor.battery_2). Only used if Exclusion Mode is set to Manual."
      default: ""
      selector:
        text:
          multiline: true

    exclusion_sensor:
      name: Exclusion Manager Sensor (Integration Mode)
      description: "Select the sensor from Device Health Exclusions Manager integration. Only used if Exclusion Mode is set to Integration."
      default: ""
      selector:
        entity:
          filter:
            - integration: device_health_exclusions
              domain: sensor

trigger:
  - platform: time
    at: !input report_time

condition:
  - condition: template
    value_template: >
      {% set send_always = not (send_only_if_issues | default(true)) %}
      {% set excluded = excluded_entities if excluded_entities is iterable and excluded_entities is not string else [] %}
      {% set low_battery_count = namespace(value=0) %}
      {% for device in states.sensor
         | selectattr('attributes.device_class', 'defined')
         | selectattr('attributes.device_class', 'eq', 'battery') %}
        {% if device.entity_id not in excluded and device.state not in ['unavailable', 'unknown'] and device.state | float(0) < battery_threshold | int %}
          {% set low_battery_count.value = low_battery_count.value + 1 %}
        {% endif %}
      {% endfor %}
      {% set low_battery = low_battery_count.value > 0 %}
      {% set unavailable_list = [] %}
      {% for entity in states
         | selectattr('state', 'in', ['unavailable', 'unknown'])
         | rejectattr('domain', 'in', ['group', 'automation', 'script', 'scene']) %}
        {% if entity.entity_id not in excluded %}
          {% set unavailable_list = unavailable_list + [entity] %}
        {% endif %}
      {% endfor %}
      {% set unavailable = unavailable_list | count > 0 %}
      {{ send_always or low_battery or unavailable }}

action:
  - service: !input notify_service
    data:
      title: "🏠 Home Assistant Device Health Report"
      message: "Device Health Report - {{ now().strftime('%B %d, %Y at %I:%M %p') }}"
      data:
        html: |
          <!DOCTYPE html>
          <html>
          <head>
            <style>
              body { font-family: Arial, sans-serif; margin: 20px; }
              h2 { border-bottom: 2px solid #ddd; padding-bottom: 10px; }
              .low-battery { color: #ff9800; }
              .unavailable { color: #f44336; }
              ul { list-style-type: none; padding-left: 0; }
              li { padding: 8px; margin: 5px 0; background: #f5f5f5; border-radius: 4px; }
              .battery-level { font-weight: bold; float: right; }
              .no-issues { color: #4caf50; font-size: 18px; }
            </style>
          </head>
          <body>
            <h1>Device Health Report</h1>
            <p>Report generated: {{ now().strftime('%B %d, %Y at %I:%M %p') }}</p>

            <h2 class="low-battery">⚠️ Low Battery Devices</h2>
            {% set excluded = excluded_entities if excluded_entities is iterable and excluded_entities is not string else [] %}
            {% set low_batteries = namespace(devices=[]) %}
            {% for device in states.sensor
               | selectattr('attributes.device_class', 'defined')
               | selectattr('attributes.device_class', 'eq', 'battery') %}
              {% if device.entity_id not in excluded and device.state not in ['unavailable', 'unknown'] and device.state | float(0) < battery_threshold | int %}
                {% set low_batteries.devices = low_batteries.devices + [device] %}
              {% endif %}
            {% endfor %}

            {% if low_batteries.devices | count > 0 %}
              <ul>
              {% for device in low_batteries.devices | sort(attribute='state') %}
                <li>
                  {{ device.name }}
                  <span class="battery-level">{{ device.state }}%</span>
                </li>
              {% endfor %}
              </ul>
            {% else %}
              <p class="no-issues">✓ All devices have sufficient battery</p>
            {% endif %}

            <h2 class="unavailable">❌ Unavailable Devices</h2>
            {% set unavailable_list = [] %}
            {% for entity in states
               | selectattr('state', 'in', ['unavailable', 'unknown'])
               | rejectattr('domain', 'in', ['group', 'automation', 'script', 'scene']) %}
              {% if entity.entity_id not in excluded %}
                {% set unavailable_list = unavailable_list + [entity] %}
              {% endif %}
            {% endfor %}
            {% set unavailable = unavailable_list %}

            {% if unavailable | count > 0 %}
              <ul>
              {% for device in unavailable | sort(attribute='name') %}
                <li>{{ device.name }} ({{ device.entity_id }})</li>
              {% endfor %}
              </ul>
            {% else %}
              <p class="no-issues">✓ All devices are responding</p>
            {% endif %}

            <hr>
            <p style="color: #888; font-size: 12px;">
              Total devices monitored: {{ states | list | count }}<br>
              Battery threshold: {{ battery_threshold }}%
            </p>
          </body>
          </html>

variables:
  battery_threshold: !input battery_threshold
  send_only_if_issues: !input send_only_if_issues
  exclusion_mode: !input exclusion_mode
  excluded_entities_manual: !input excluded_entities
  exclusion_sensor: !input exclusion_sensor
  excluded_entities: >
    {% if exclusion_mode == 'integration' %}
      {{ state_attr(exclusion_sensor, 'excluded_entities') | default([]) }}
    {% else %}
      {{ excluded_entities_manual.split(',') | map('trim') | list if excluded_entities_manual else [] }}
    {% endif %}

mode: single